Update patch set 1
Patch Set 1:

Uhhh, this breaks build.  Was this tested before merge?

packages/apps/Apollo/src/com/andrew/apollo/MusicPlaybackService.java:51: error: package android.support.v7.graphics does not exist
import android.support.v7.graphics.Palette;
                                  ^
packages/apps/Apollo/src/com/andrew/apollo/MusicPlaybackService.java:1445: error: cannot find symbol
        final Palette p = Palette.generate(getAlbumArt());
              ^
  symbol:   class Palette
  location: class MusicPlaybackService
packages/apps/Apollo/src/com/andrew/apollo/MusicPlaybackService.java:1445: error: cannot find symbol
        final Palette p = Palette.generate(getAlbumArt());
                          ^
  symbol:   variable Palette
  location: class MusicPlaybackService
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: packages/apps/Apollo/src/com/andrew/apollo/utils/ApolloUtils.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

Patch-set: 1
Reviewer: Chris Holmes <6749@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0