Apollo: Ignore playlist when name is null.
This will avoid nex crash:

FATAL EXCEPTION: main
java.lang.IllegalArgumentException: the bind value at index 1 is null
 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:366)
 	at android.content.ContentResolver.query(ContentResolver.java:372)
 	at android.content.ContentResolver.query(ContentResolver.java:315)
 	at com.andrew.apollo.utils.MusicUtils.getIdForPlaylist(MusicUtils.java:669)
 	at com.andrew.apollo.utils.MusicUtils.makePlaylistMenu(MusicUtils.java:1146)
 	at com.andrew.apollo.ui.fragments.QueueFragment.onCreateContextMenu(QueueFragment.java:215)

Change-Id: Ib60a55f54fedf18cf900c6e492c5b4135e5c86d8